# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - id: pipeops         # <--- Single build definition with a unique id
    binary: pipeops     # <--- The actual name of the generated binary <--- Add your desired binary name here
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - linux
      - windows
      - darwin
      
    goarch:
      - "386"
      - amd64
      - arm
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  
    # Header for the release body.
  # Adds a custom, friendly introduction to each release.
  header: |
    ---
    ## 🚀 New Release: {{ .ProjectName }} v{{ .Version }} ({{ .Date }})

    We’re excited to announce the release of **{{ .ProjectName }} v{{ .Version }}**!
    This update brings the latest features, improvements, and fixes to help you get the best out of PipeOps CLI.

  # Footer for the release body.
  # Adds a custom closing message to thank contributors or point to further resources.
  footer: |
    ---
    ## 📝 Additional Information

    - **Download**: You can find platform-specific binaries below.
    - **Contribute**: Got feedback or ideas? Open an issue or a PR on [GitHub](https://github.com/PipeOpsHQ/pipeops-cli).
    - **Documentation**: Check out our [docs](https://docs.pipeops.io).

    ## 💬 Stay Connected

    Join our community to stay updated:
    - [Twitter](https://twitter.com/pipeops)  
    - [Discord](https://discord.gg/pipeops)

    **Thank you for using {{ .ProjectName }}!** ❤️