# GoReleaser configuration for PipeOps CLI
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: pipeops
    binary: pipeops
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
      - -X github.com/PipeOpsHQ/pipeops-cli/cmd.Version={{.Version}}
      - -X github.com/PipeOpsHQ/pipeops-cli/cmd.BuildDate={{.Date}}
      - -X github.com/PipeOpsHQ/pipeops-cli/cmd.GitCommit={{.Commit}}
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

release:
  draft: false
  prerelease: auto
  header: |
    ## 🚀 PipeOps CLI v{{ .Version }}

    **Release Date:** {{ .Date }}

    Welcome to the latest release of PipeOps CLI! This version includes new features, improvements, and bug fixes.

    ### 📦 Installation

    #### Quick Install (Recommended)
    ```bash
    # macOS/Linux
    curl -fsSL https://raw.githubusercontent.com/PipeOpsHQ/pipeops-cli/main/install.sh | sh

    # Or using Homebrew (macOS/Linux)
    brew tap pipeops/pipeops
    brew install pipeops
    ```

    #### Manual Download
    Download the appropriate binary for your platform from the assets below.

  footer: |
    ---
    ## 📖 Documentation & Support

    - **Documentation**: [docs.pipeops.io](https://docs.pipeops.io)
    - **Getting Started**: `pipeops --help`
    - **Report Issues**: [GitHub Issues](https://github.com/PipeOpsHQ/pipeops-cli/issues)

    ## 🌟 Community

    - **Discord**: [Join our community](https://discord.gg/pipeops)
    - **Twitter**: [@PipeOpsHQ](https://twitter.com/pipeops)
    - **Website**: [pipeops.io](https://pipeops.io)

    **Thanks for using PipeOps CLI!** 🙏

# Homebrew
brews:
  - name: pipeops
    repository:
      owner: pipeops
      name: homebrew-pipeops
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/PipeOpsHQ/pipeops-cli
    description: Official command line tool for PipeOps
    license: MIT
    commit_author:
      name: pipeops-bot
      email: bot@pipeops.io
    install: |
      bin.install "pipeops"
    test: |
      system "#{bin}/pipeops", "version"

# Linux packages (.deb, .rpm)
nfpms:
  - id: packages
    package_name: pipeops
    vendor: PipeOps
    homepage: https://github.com/PipeOpsHQ/pipeops-cli
    maintainer: PipeOps Team <support@pipeops.io>
    description: Official command line tool for PipeOps
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/pipeops/copyright
      - src: ./README.md
        dst: /usr/share/doc/pipeops/README.md
    scripts:
      postinstall: scripts/postinstall.sh
