name: Code Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 18 * * 0" # Weekly on Sundays at 18:00 UTC

jobs:
  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history for better analysis if needed

      # Step 2: Initialize CodeQL for Go language
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go

      # Step 3: Autobuild (builds the code for analysis)
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      # Step 4: Perform CodeQL Analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
