name: Auto Version and Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: read
  issues: read
  packages: write
  actions: write

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug Git State
        run: |
          echo "Current commit: $(git rev-parse HEAD)"
          echo "Current tag: $(git describe --tags --exact-match || echo 'No tag found')"
          git show

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          cache: true

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          default_bump: patch
          release_branches: develop
          create_annotated_tag: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
