name: Auto Version and Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: read
  issues: read
  packages: write
  actions: write

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug Git State
        run: |
          echo "Current commit: $(git rev-parse HEAD)"
          echo "Current tag: $(git describe --tags --exact-match || echo 'No tag found')"
          git show

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          cache: true

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # If you're actually pushing from `main`:
          release_branches: main
          default_bump: patch
          create_annotated_tag: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
